"""Render a RepoWatch report as the body of the "RepoWatch audit" issue."""

from __future__ import annotations

from collections import Counter

# GitHub rejects issue bodies over 65,536 characters.
MAX_BODY = 60_000
SEVERITY_ORDER = ("critical", "high", "medium", "low")


def _dependabot_cell(d: dict) -> str:
    if d.get("dependabot_disabled"):
        return "turned off"
    if d.get("access_denied"):
        return "no access"
    if d.get("error"):
        return "error"
    findings = d.get("findings", [])
    if not findings:
        return "0 open"
    counts = Counter(f.get("severity", "unknown") for f in findings)
    parts = [f"{counts[s]} {s}" for s in SEVERITY_ORDER if counts[s]]
    return f"**{len(findings)} open** ({', '.join(parts)})" if parts else f"**{len(findings)} open**"


def _count(check: dict, key: str = "findings") -> str:
    if check.get("error"):
        return "error"
    n = len(check.get(key, []))
    return f"**{n}**" if n else "0"


def _pii_cell(p: dict) -> str:
    if p.get("error"):
        return "error"
    review = [f for f in p.get("findings", []) if not f.get("likely_benign")]
    return f"**{len(review)}** to review" if review else "0 to review"


def render(report: dict, trigger: str) -> str:
    repos = report.get("repos", [])
    lines = [
        f"RepoWatch audited **{report.get('repos_scanned', len(repos))}** repositories "
        f"in `{report.get('org')}` at {report.get('generated_at', '')[:16].replace('T', ' ')} UTC "
        f"({trigger}).",
        "",
        "Comment `/repowatch run` on this issue to run the audit again.",
        "",
        "| Repository | Dependabot | Stale PRs (>10 days) | Conflict merges | Untested commits (last 20) | PII |",
        "|---|---|---|---|---|---|",
    ]
    for r in sorted(repos, key=lambda r: r["repo"].lower()):
        lines.append(
            f"| `{r['repo']}` | {_dependabot_cell(r['dependabot'])} "
            f"| {_count(r['stale_prs'], 'stale_prs')} | {_count(r['conflict_merges'])} "
            f"| {_count(r['untested_deploys'])} | {_pii_cell(r['pii'])} |"
        )

    lines += ["", "## Details", ""]
    any_detail = False
    for r in sorted(repos, key=lambda r: r["repo"].lower()):
        items = []
        for f in r["dependabot"].get("findings", []):
            items.append(f"- Dependabot **{f.get('severity')}**: `{f.get('package')}`, {f.get('summary')} ([alert]({f.get('url')}))")
        for pr in r["stale_prs"].get("stale_prs", []):
            items.append(f"- Stale PR [#{pr.get('number')}]({pr.get('url')}): {pr.get('title')}, open {pr.get('days_open')} days")
        for f in r["conflict_merges"].get("findings", []):
            items.append(f"- Merge with a conflict marker: [`{f.get('sha')}`]({f.get('url')}) {f.get('message_summary')}")
        for f in r["pii"].get("findings", []):
            if not f.get("likely_benign"):
                items.append(
                    f"- Possible PII ({f.get('kind')}) in `{f.get('path')}`: `{f.get('masked_excerpt')}`. "
                    "A pattern match for review, not a confirmed leak."
                )
        errors = [f"{name}: {c.get('error')}" for name, c in r.items() if isinstance(c, dict) and c.get("error")]
        items += [f"- Check failed, {e}" for e in errors]
        if items:
            any_detail = True
            lines += [f"### `{r['repo']}`", "", *items, ""]
    if not any_detail:
        lines += ["No Dependabot alerts, stale PRs, conflict merges or PII to review.", ""]

    sprawl = report.get("sprawl") or {}
    if sprawl.get("over_threshold") or sprawl.get("near_duplicates"):
        lines += ["## Repository sprawl", ""]
        if sprawl.get("over_threshold"):
            lines.append(f"- {sprawl.get('total_active_repos')} active repositories, over the threshold of 15.")
        for d in sprawl.get("near_duplicates", []):
            lines.append(f"- Similar names: `{d['repo_a']}` and `{d['repo_b']}` ({d['similarity']:.2f}).")
        lines.append("")

    lines += [
        "## How to read this",
        "",
        "- **Dependabot**: *turned off* means alerts were never enabled for that repository; *no access* means "
        "RepoWatch was not granted the Dependabot alerts permission. Neither is a clean result.",
        "- **Untested commits** counts recent commits with no check run named like a Playwright or Vitest job. "
        "Repositories that test with other tools will show every commit as untested.",
        "- **PII** matches are regex candidates, shown masked. Matches RepoWatch marks as likely benign (paths containing test, spec, fixture, example or sample, and Markdown files) are not listed.",
        "",
        "<sub>Generated by the RepoWatch GitHub App. Read-only except for this issue.</sub>",
    ]
    body = "\n".join(lines)
    if len(body) > MAX_BODY:
        body = body[:MAX_BODY] + "\n\n_Report truncated to fit GitHub's issue size limit._"
    return body
